### ISSUE TITLE
ui-table allow wider than 8

### ISSUE THREAD

**Issue by team-tech-works-uk** [node-red/node-red-ui-nodes#69]
i use a hi-def widget grid .. my dashboard group width is 50 .. but table max width seems to be 8 :-( is there a simple way to allow wider widths? many thanks

**Comment by knolleary** [comment]
Hi @team-tech-works-uk 

as per the issue template you've deleted, we prefer general 'how-to' questions to be directed to the forum where the whole community can help, rather than rely on the core developers.

A widget's width will be capped by the group it is in. So the first thing to check is whether the table node is in the group you think it is.

**Comment by Christian-Me** [comment]
I don't see any limitation here .... I'm using ui-table with 19 grid unit width
